# Generated by Django 5.0.2 on 2024-03-16 23:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Rating', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Level', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=500)),
                ('Price', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('URL', models.CharField(max_length=500)),
                ('Image', models.ImageField(blank=True, default='Images/pictureplaceholder.jpg', null=True, upload_to='Images/')),
                ('Description', models.CharField(max_length=500)),
                ('Platform', models.CharField(max_length=50)),
                ('Certificate', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Duration', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('Learning_Type', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('Enrolled', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('Reviews', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('Last_Updated', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('Category', models.CharField(max_length=100)),
                ('Instructors', models.CharField(max_length=500)),
                ('Skill', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpages.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpages.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpages.user')),
            ],
        ),
    ]
