# Generated by Django 5.0.2 on 2024-03-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Rating', models.CharField(max_length=100)),
                ('Level', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=500)),
                ('Price', models.CharField(max_length=500)),
                ('URL', models.CharField(max_length=500)),
                ('Image', models.ImageField(blank=True, default='Images/pictureplaceholder.jpg', null=True, upload_to='Images/')),
                ('Description', models.CharField(max_length=500)),
                ('Platform', models.CharField(max_length=50)),
                ('Certificate', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=500)),
                ('Learning_Type', models.CharField(max_length=500)),
                ('Enrolled', models.CharField(max_length=500)),
                ('Reviews', models.CharField(max_length=500)),
                ('Last_Updated', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('Category', models.CharField(max_length=100)),
                ('Instructors', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=800)),
            ],
        ),
    ]
