# Generated by Django 5.0.2 on 2024-03-17 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Skill',
        ),
        migrations.AlterField(
            model_name='course',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpages.skill'),
        ),
    ]
