# Generated by Django 4.2 on 2024-03-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0004_alter_course_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Description',
            field=models.CharField(max_length=1500),
        ),
    ]
