# Generated by Django 5.0.2 on 2024-03-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0007_alter_myuser_gender_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='language',
            field=models.CharField(choices=[('E', 'English'), ('A', 'Arabic'), ('K', 'Korean'), ('G', 'German')], max_length=1),
        ),
    ]
