# Generated by Django 5.0.2 on 2024-03-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0008_alter_myuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('E', 'English'), ('A', 'Arabic'), ('K', 'Korean'), ('G', 'German')], max_length=1),
        ),
    ]
