# Generated by Django 5.0.2 on 2024-03-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0009_alter_profile_birthdate_alter_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
