# Generated by Django 5.0.2 on 2024-03-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0011_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
