# Generated by Django 5.0.2 on 2024-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0012_alter_profile_birthdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myUser',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='Images/defaultprofile.jpg', null=True, upload_to='Images/profile_pics'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Image',
            field=models.ImageField(blank=True, default='Images/pictureplaceholder.jpg', null=True, upload_to='Images/course_pics'),
        ),
    ]
