# Generated by Django 5.0.2 on 2024-03-20 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0013_delete_myuser_profile_image_alter_course_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
