# Generated by Django 5.0.2 on 2024-05-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0021_alter_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='takenCourses',
            field=models.ManyToManyField(to='mainpages.course'),
        ),
    ]
